In [2]:
import numpy as np

In [27]:
R_x = np.array([[5, -1, -2],[-1, 5, -1],[-2, -1, 5]])
r_yx = np.array([1, 5.3, -3.9]).reshape((3,1))

w_o = np.dot(np.linalg.inv(R_x),  r_yx)


In [31]:
np.linalg.inv(R_x)

array([[0.26373626, 0.07692308, 0.12087912],
       [0.07692308, 0.23076923, 0.07692308],
       [0.12087912, 0.07692308, 0.26373626]])

In [28]:
w_o

array([[ 0.2],
       [ 1. ],
       [-0.5]])

In [29]:
eigenvalues = np.linalg.eigvals(R_x)
# alpha between 0 and 1/7

In [30]:
eigenvalues

array([2.26794919, 7.        , 5.73205081])